loki:
  image:
    tag: 2.9.3
  config:
    server:
      http_listen_port: 3100
    schema_config:
      configs:
        - from: 2020-10-24
          store: boltdb-shipper
          object_store: s3
          schema: v11
          index:
            prefix: loki_index_
            period: 24h   #test-values
    storage_config:
      boltdb_shipper:
        shared_store: s3
        active_index_directory: /data/loki/index
        cache_location: /data/loki/cache
      aws:
        s3: s3://eu-central-1/k8s-logging-bucket
        region: eu-central-1
    chunk_store_config:
      max_look_back_period: 0s
    table_manager:
      retention_deletes_enabled: true
      retention_period: 36h   #test-values

  persistence:
    enabled: true
    storageClassName: local-path
    accessModes:
      - ReadWriteOnce
    size: 2Gi   #test-values

promtail:
  enabled: true
  config:
    clients:
      - url: http://loki.logging.svc:3100/loki/api/v1/push
    positions:
      filename: /var/promtail/positions.yaml
    scrape_configs:
      - job_name: system
        static_configs:
          - targets:
              - localhost
            labels:
              job: varlogs
              __path__: /var/log/*.log
  extraVolumeMounts:
    - name: promtail-positions
      mountPath: /var/promtail
  extraVolumes:
    - name: promtail-positions
      emptyDir: {}